### ISSUE TITLE
Can it support Azure openai? Or an endpoint that can be customized for api access?

### ISSUE THREAD

**Issue by suikaremilia** [nalgeon/pokitoki#18]
https://learn.microsoft.com/en-us/azure/cognitive-services/openai/overview

Azure also has openai service, which can do more customizable things than openai, so can the bot support azure openai?

**Comment by nalgeon** [comment]
According to the link, both gpt-3.5 and gpt-4 are not yet publicly available on Azure. Do you already have access to them?

**Comment by suikaremilia** [comment]
https://learn.microsoft.com/en-us/azure/cognitive-services/openai/chatgpt-quickstart?tabs=command-line&pivots=programming-language-python

Like openai, they use two items as a preview version, but they can easily apply for access rights.

GPT4 needs to wait, GPT-3.5 is actually open.

**Comment by nalgeon** [comment]
Do you have access to the GPT 3.5 Azure OpenAI API? Will you be able to test the implementation if the bot supports it?

**Comment by suikaremilia** [comment]
Yes, I can test it.

**Comment by nalgeon** [comment]
Okay, please try with the latest bot version ([5fa0144](https://github.com/nalgeon/pokitoki/commit/5fa0144881dbe32701decc3b04b26d173f03e4b9)). You'll need to set the actual values for all three parameters in the `openai.azure` config property (`endpoint`, `version`, and `deployment`):

```yaml
openai:
    # ...
    azure:
        endpoint: https://example-endpoint.openai.azure.com
        version: 2023-03-15-preview
        deployment: deployment-name
```
